### PR TITLE
Upgrade to 3.4.1

### PR DESCRIPTION
**Pull request by deshipu**
Also, add .map files for the minified versions.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Thanks!

**Comment by deshipu** [comment]
Thank you!
Can you do a release, or can I do it somehow?

**Comment by ThomasWaldmann** [comment]
You are also maintainer on pypi, so you can do a release.

If it helps, I can also do it.

**Comment by deshipu** [comment]
Thank you, I will do it tomorrow.

**Pull request merged**
